---
driver:
  name: azurerm
  subscription_id: <%= ENV['AZURE_SUBSCRIPTION_ID'] %>
  location: 'Central US'
  machine_size: 'Standard_A2'

platforms:
  - name: windows-2012r2-wmf4
    provisioner:
      dsc_local_configuration_manager_version: wmf4_with_update
    driver:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-DataCenter:latest
  - name: windows-tp4-wmf5
    provisioner:
      dsc_local_configuration_manager_version: wmf5
    driver:
      image_urn: MicrosoftWindowsServer:WindowsServer:Windows-Server-Technical-Preview:latest
