---
driver:
  name: vagrant
  linked_clones: true
  gui: false
  communicator: winrm
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: dsc

transport:
  name: winrm

verifier:
  name: pester
  test_folder: Tests/Integration

platforms:
  - name: windows-2012r2-wmf4
    driver:
      box: smurawski/2012R2-wmf4
      network: 
        - ["forwarded_port", {guest: 80, host: 8080}]
    provisioner:
      dsc_local_configuration_manager_version: wmf4_with_update
  - name: windows-2012r2-wmf5
    driver:
      box: smurawski/2012R2-wmf5
      network:
        - ["forwarded_port", {guest: 80, host: 8081}]
    provisioner:
      dsc_local_configuration_manager_version: wmf5


suites:
  - name: MSFT_xWebsite
    provisioner: 
      configuration_script_folder: Tests/Integration/MSFT_xWebsite
      configuration_script: MSFT_xWebsite.config.ps1
      configuration_name: MSFT_xWebsite_Config


